name: Deploy to GitHub Pages
on:
  push:
    branches: ["**"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Documentation
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          mkdir -p docs
          pandoc -f markdown -t html -s README.md --metadata title="Pinions" -o docs/index.html
          cp target/readme.html docs/index.html
      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions Bot: .github/workflows/....gh-pages.yml"
          git config --global user.email "you@example.com"
          git add --all
          git commit -m "Pushing to GitHub Pages: https://pinponik.github.io/pinions/" || echo "No changes to commit"
          git push
