name: CI

on:
  push:
    branches: ["**"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo install cargo-hack
        run: cargo install cargo-hack
      - name: Cargo hack check --each-feature
        run: cargo hack check --each-feature
      - name: Cargo clippy
        run: cargo clippy
