name: CI

on:
  push:
    branches: ["**"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Cargo check
        run: cargo check
      - name: Cargo clippy
        run: cargo clippy
      - name: Documentation
        run: cargo doc && cp target/doc/pinions/index.html docs/index.html
